"""wiki 子系统：frontmatter / 实体注册表 / 存储层 / 嵌入 / 检索索引 / 时效计算 / 判定。"""

from researchwiki.wiki.embeddings import (
    CachedEmbeddingProvider,
    EmbeddingError,
    EmbeddingProvider,
    MockEmbeddingProvider,
    OpenAICompatibleEmbedding,
    get_embedding_provider,
)
from researchwiki.wiki.entities import Entity, EntityRegistry, slugify
from researchwiki.wiki.freshness import (
    FRESHNESS_FRESH,
    FRESHNESS_REVIEW_DUE,
    FRESHNESS_STALE,
    FreshnessSettings,
    FreshnessState,
    evaluate_freshness,
    freshness_counts,
    freshness_queue,
)
from researchwiki.wiki.freshness import from_config as freshness_from_config
from researchwiki.wiki.frontmatter import NoteMeta, SourceRef, dump, parse
from researchwiki.wiki.index import (
    SearchIndex,
    SearchMatch,
    WikiSettings,
    freshness_factor,
    rrf_fuse,
    wiki_search,
    wiki_settings,
)
from researchwiki.wiki.prior import (
    PRIOR_CONTEXT_LABEL,
    PriorContext,
    PriorHit,
    ensure_index_fresh,
    format_prior_context,
    retrieve_priors,
)
from researchwiki.wiki.store import Conflict, Note, Page, WikiStore
from researchwiki.wiki.verification import (
    ACTION_MERGE,
    ACTION_NONE,
    ACTION_OPEN_CONFLICT,
    ACTION_REFRESH_REVIEWED_AT,
    ACTION_SUPERSEDE,
    VERDICT_ACTIONS,
    VERDICT_CONFLICTING,
    VERDICT_CONSISTENT,
    VERDICT_MORE_SPECIFIC,
    VERDICT_NEWER,
    VERDICT_UNCERTAIN,
    VERDICTS,
    EvidenceComparison,
    EvidenceItem,
    VerificationSettings,
    compare_batch,
    compare_prior_and_evidence,
    detect_slot_conflicts,
    token_similarity,
)

__all__ = [
    "ACTION_MERGE",
    "ACTION_NONE",
    "ACTION_OPEN_CONFLICT",
    "ACTION_REFRESH_REVIEWED_AT",
    "ACTION_SUPERSEDE",
    "CachedEmbeddingProvider",
    "Conflict",
    "EmbeddingError",
    "EmbeddingProvider",
    "Entity",
    "EntityRegistry",
    "EvidenceComparison",
    "EvidenceItem",
    "FRESHNESS_FRESH",
    "FRESHNESS_REVIEW_DUE",
    "FRESHNESS_STALE",
    "FreshnessSettings",
    "FreshnessState",
    "MockEmbeddingProvider",
    "Note",
    "NoteMeta",
    "OpenAICompatibleEmbedding",
    "PRIOR_CONTEXT_LABEL",
    "Page",
    "PriorContext",
    "PriorHit",
    "SearchIndex",
    "SearchMatch",
    "SourceRef",
    "VERDICT_ACTIONS",
    "VERDICT_CONFLICTING",
    "VERDICT_CONSISTENT",
    "VERDICT_MORE_SPECIFIC",
    "VERDICT_NEWER",
    "VERDICT_UNCERTAIN",
    "VERDICTS",
    "VerificationSettings",
    "WikiSettings",
    "WikiStore",
    "compare_batch",
    "compare_prior_and_evidence",
    "detect_slot_conflicts",
    "dump",
    "ensure_index_fresh",
    "evaluate_freshness",
    "format_prior_context",
    "freshness_counts",
    "freshness_factor",
    # from_config 在包内重名风险高（formation/prior/dedup 各有同名解析器），
    # 故以 freshness_from_config 导出；freshness.from_config 仍是模块内的正式名。
    "freshness_from_config",
    "freshness_queue",
    "get_embedding_provider",
    "parse",
    "retrieve_priors",
    "rrf_fuse",
    "slugify",
    "token_similarity",
    "wiki_search",
    "wiki_settings",
]
